### ISSUE TITLE
Does not work in <style></style> tags

### ISSUE THREAD

**Issue by aubreyz** [j5v/markdown-todos#8]
Although it works great in styles.less file I don't want to influence every file. You suggest it can be pasted into <style> tag in md file itself. This does not however work.

**Comment by j5v** [comment]
Yes, I think that's a leftover from when I first made this file, and the CSS specificity was simpler. The markdown plugin has changed a few times, and by following suit with extra specifiers, I've lost compatibility with the in-document <style> variant.

I think it might be possible to remove some of the class specifiers to get it to work.

**Comment by aubreyz** [comment]
Thanks - I think it would be really useful to make a CSS variant that is OK for punching at the top of the file. I'll have hundreds of markdown files and this is quite a lot of CSS to apply universally.

**Comment by j5v** [comment]
I'll update this to VSCode soon.

**Comment by j5v** [comment]
Closing; VSCode had succeeded Atom, and we'll support VSCode.
